limit user input

diff --git a/src/earthlive-daemon.in b/src/earthlive-daemon.in
--- a/src/earthlive-daemon.in
+++ b/src/earthlive-daemon.in
@@ -51,19 +51,20 @@ while ((1)); do
 			url_time="${now:0:4}/${now:5:2}/${now:8:2}/${now:11:2}${now:14:2}${now:17:2}"
 			# yyyy/mm/dd/hhmmss
 			
+			rm -f ${opt_store}/tile_*.png
 			for ((i=0; i<opt_density; i++)); do
 				for ((k=0; k<opt_density; k++)); do
 					url_suffix="_${i}_${k}.png"
 					url="${cdn_prefix}${url_prefix}${url_time}${url_suffix}"
 					curl -Ss -o "${opt_store}/tile_${k}_${i}.png" "$url"
-					(( $? )) || log 2 "Obtained tile ${k}_${i} at ${now}"
+					(( $? )) || log 2 "Obtained tile ${k}_${i} at ${now}" && log 1 "Failed to get tile ${k}_${i} at ${now}"
 				done
 			done
 			
 			if [[ $opt_density -eq 1 ]]; then
-				cp "${opt_store}/final.png"
+				cp "${opt_store}/tile_0_0.png" "${opt_store}/final.png"
 			else
-				montage ${opt_store}/tile_*.png -tile ${opt_density}x${opt_density} -geometry +0+0 ${opt_store}/final.png
+				montage "${opt_store}/tile_*_*.png" -tile ${opt_density}x${opt_density} -geometry +0+0 "${opt_store}/final.png"
 			fi
 			# orig.png will be a concatenated picture in the future versions
 		fi
